###################################################
#       _   _            _                        #
#      | | | |          (_)                       #
#      | |_| | ___  _ __ _ _______  _ __          #
#      |  _  |/ _ \| '__| |_  / _ \| '_  \        #
#      | | | | (_) | |  | |/ / (_) | | | |        #
#      \_| |_/\___/|_|  |_/___\___/|_| |_|        #
###################################################
# This file is part of Horizon (c).
# Copyright (c) 2018 Horizon Dev Team.
#
# Base Author - Sagun Khosla. (sagunxp@gmail.com)
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this library.  If not, see <http://www.gnu.org/licenses/>.
###################################################

stages:
  - debug
  - release

variables: &base_vars
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: 'horizon'
  MYSQL_USER: 'ragnarok'
  MYSQL_ROOT_PASSWORD: 'ragnarok'
  MYSQL_PASSWORD: 'ragnarok'
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  GIT_DEPTH: '3'
  DEBIAN_COMMON_PACKAGES: cmake default-mysql-server default-mysql-client libmysqlcppconn-dev libboost-all-dev libssl-dev libreadline-dev

.prerequisites: &prerequisites
  before_script:
    - echo "Building $CI_BUILD_NAME"
    - uname -a
    - ${PKG_CMD} update
    - ${PKG_CMD} install ${INSTALL_PACKAGES}
    - ${PKG_CMD} install ${INSTALL_COMPILER}
    - mysql --version
    - service mysql start
    - echo "CREATE USER '${MYSQL_USER}'@'mysql' IDENTIFIED BY '${MYSQL_PASSWORD}';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql
    - echo "CREATE DATABASE ${MYSQL_DATABASE};"
    - echo "GRANT ALL ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'mysql';"
    - echo "USE ${MYSQL_DATABASE}; SELECT 'OK'" | mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --host=mysql
  services:
    - mysql:latest

# Compilers
debian:buster-gcc:
  <<: *prerequisites
  stage: debug
  image: debian:buster
  variables:
    <<: *base_vars
    PKG_CMD: apt-get --yes
    INSTALL_PACKAGES: git ${DEBIAN_COMMON_PACKAGES}
    INSTALL_COMPILER: g++-7
  script:
    - ${INSTALL_COMPILER} --version
    - export CXX=/usr/bin/${INSTALL_COMPILER}
    - git clone https://github.com/gabime/spdlog.git
    - cd spdlog; mkdir build; cd build; cmake ../
    - make install -j 4; cd ..; cd ..;
    - ./horizon build
    - cp bin/config/inter-server.lua.dist bin/config/inter-server.lua
    - cp bin/config/auth-server.lua.dist bin/config/auth-server.lua
    - cp bin/config/char-server.lua.dist bin/config/char-server.lua
    - cp bin/config/zone-server.lua.dist bin/config/zone-server.lua
    - mkdir bin/logs
    - ./horizon inter bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon auth bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon char bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon zone bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10

debian:buster-clang:
  <<: *prerequisites
  stage: debug
  image: debian:buster
  variables:
    <<: *base_vars
    PKG_CMD: apt-get --yes
    INSTALL_PACKAGES: git ${DEBIAN_COMMON_PACKAGES}
    INSTALL_COMPILER: clang
  script:
    - ${INSTALL_COMPILER} --version
    - export CXX=/usr/bin/${INSTALL_COMPILER}++
    - git clone https://github.com/gabime/spdlog.git
    - cd spdlog; mkdir build; cd build; cmake ../
    - make install -j 4; cd ..; cd ..;
    - ./horizon build
    - cp bin/config/inter-server.lua.dist bin/config/inter-server.lua
    - cp bin/config/auth-server.lua.dist bin/config/auth-server.lua
    - cp bin/config/char-server.lua.dist bin/config/char-server.lua
    - cp bin/config/zone-server.lua.dist bin/config/zone-server.lua
    - mkdir bin/logs
    - ./horizon inter bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon auth bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon char bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon zone bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10

debian:stretch-gcc:
  <<: *prerequisites
  stage: debug
  image: debian:stretch
  variables:
    <<: *base_vars
    PKG_CMD: apt-get --yes
    INSTALL_PACKAGES: git ${DEBIAN_COMMON_PACKAGES}
    INSTALL_COMPILER: g++-6
  script:
    - ${INSTALL_COMPILER} -v
    - export CXX=/usr/bin/${INSTALL_COMPILER}
    - git clone https://github.com/gabime/spdlog.git
    - cd spdlog; mkdir build; cd build; cmake ../
    - make install -j 4; cd ..; cd ..;
    - ./horizon build
    - cp bin/config/inter-server.lua.dist bin/config/inter-server.lua
    - cp bin/config/auth-server.lua.dist bin/config/auth-server.lua
    - cp bin/config/char-server.lua.dist bin/config/char-server.lua
    - cp bin/config/zone-server.lua.dist bin/config/zone-server.lua
    - mkdir bin/logs
    - ./horizon inter bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon auth bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon char bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon zone bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10

debian:stretch-clang:
  <<: *prerequisites
  stage: debug
  image: debian:stretch
  variables:
    <<: *base_vars
    PKG_CMD: apt-get --yes
    INSTALL_PACKAGES: git ${DEBIAN_COMMON_PACKAGES}
    INSTALL_COMPILER: clang
  script:
    - ${INSTALL_COMPILER} --version
    - export CXX=/usr/bin/${INSTALL_COMPILER}++
    - git clone https://github.com/gabime/spdlog.git
    - cd spdlog; mkdir build; cd build; cmake ../
    - make install -j 4; cd ..; cd ..;
    - ./horizon build
    - cp bin/config/inter-server.lua.dist bin/config/inter-server.lua
    - cp bin/config/auth-server.lua.dist bin/config/auth-server.lua
    - cp bin/config/char-server.lua.dist bin/config/char-server.lua
    - cp bin/config/zone-server.lua.dist bin/config/zone-server.lua
    - mkdir bin/logs
    - ./horizon inter bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon auth bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon char bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
    - ./horizon zone bin --test-run --dbuser=${MYSQL_USER} --dbhost=mysql --dbdatabase=${MYSQL_DATABASE} --dbpassword=${MYSQL_PASSWORD} --dbthreads=10
