stages:
  - primary

variables: &base_vars
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: 'horizon'
  MYSQL_USER: 'ragnarok'
  MYSQL_ROOT_PASSWORD: 'ragnarok'
  MYSQL_PASSWORD: 'ragnarok'
  MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
  GIT_DEPTH: '1'
  DEBIAN_COMMON_PACKAGES: cmake mysql libmysqlcppconn-dev libboost-all-dev libssl-dev libspdlog-dev

.prerequisites: &prerequisites
  before_script:
    - echo "Building $CI_BUILD_NAME"
    - uname -a
    - apt-get update --yes
    - apt-get install --yes cmake libmysqlcppconn-dev libboost-all-dev libssl-dev libspdlog-dev libyaml-cpp-dev mysql-server mysql-client
    - mysql --version
    - service mysql start
    - echo "CREATE USER '${MYSQL_USER}'@'mysql' IDENTIFIED BY '${MYSQL_PASSWORD}';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql
    - echo "CREATE DATABASE ${MYSQL_DATABASE};"
    - echo "GRANT ALL ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'mysql';"
    - echo "USE ${MYSQL_DATABASE}; SELECT 'OK'" | mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --host=mysql
  services:
    - mysql:latest

# Compilers

one:cmake:
  <<: *prerequisites
  stage: primary
  image: gcc
  variables:
    <<: *base_vars
  script:
    - mkdir build
    - cd build
    - rm -rf ./*
    - cmake ../
    - make install -j 4
    - cd ../bin
    - ./auth --test-run
    - ./char --test-run
