###################################################
#       _   _            _                        #
#      | | | |          (_)                       #
#      | |_| | ___  _ __ _ _______  _ __          #
#      |  _  |/ _ \| '__| |_  / _ \| '_  \        #
#      | | | | (_) | |  | |/ / (_) | | | |        #
#      \_| |_/\___/|_|  |_/___\___/|_| |_|        #
###################################################
# This file is part of Horizon (c).
# Copyright (c) 2018 Horizon Dev Team.
#
# Base Author - Sagun Khosla. (sagunxp@gmail.com)
#
# Under a proprietary license this file is not for use
# or viewing without permission.
###################################################

stages:
  - primary

variables: &base_vars
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: 'horizon'
  MYSQL_USER: 'ragnarok'
  MYSQL_ROOT_PASSWORD: 'ragnarok'
  MYSQL_PASSWORD: 'ragnarok'
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  GIT_DEPTH: '3'
  DEBIAN_COMMON_PACKAGES: cmake mysql libmysqlcppconn-dev libboost-all-dev libssl-dev libspdlog-dev

.prerequisites: &prerequisites
  before_script:
    - echo "Building $CI_BUILD_NAME"
    - uname -a
    - ${PKG_CMD} update
    - ${PKG_CMD} install $INSTALL_PACKAGES
    - mysql --version
    - service mysql start
    - echo "CREATE USER '${MYSQL_USER}'@'mysql' IDENTIFIED BY '${MYSQL_PASSWORD}';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql
    - echo "CREATE DATABASE ${MYSQL_DATABASE};"
    - echo "GRANT ALL ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'mysql';"
    - echo "USE ${MYSQL_DATABASE}; SELECT 'OK'" | mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --host=mysql
  services:
    - mysql:latest

# Compilers
debian:buster:
  <<: *prerequisites
  stage: primary
  image: debian:buster
  variables:
    <<: *base_vars
    PKG_CMD: apt-get --yes
    INSTALL_PACKAGES: cmake default-mysql-server default-mysql-client libmysqlcppconn-dev libboost-all-dev libssl-dev libspdlog-dev libyaml-cpp-dev
  script:
    - ./gitlab-ci.sh

debian:stretch:
  <<: *prerequisites
  stage: primary
  image: debian:stretch
  variables:
    <<: *base_vars
    PKG_CMD: apt-get --yes
    INSTALL_PACKAGES: cmake default-mysql-server default-mysql-client libmysqlcppconn-dev libboost-all-dev libssl-dev libspdlog-dev libyaml-cpp-dev
  script:
    - ./gitlab-ci.sh