###################################################
#       _   _            _                        #
#      | | | |          (_)                       #
#      | |_| | ___  _ __ _ _______  _ __          #
#      |  _  |/ _ \| '__| |_  / _ \| '_  \        #
#      | | | | (_) | |  | |/ / (_) | | | |        #
#      \_| |_/\___/|_|  |_/___\___/|_| |_|        #
###################################################
# This file is part of Horizon (c).
# Copyright (c) 2018 Horizon Dev Team.
#
# Base Author - Sagun Khosla. (sagunxp@gmail.com)
#
# Under a proprietary license this file is not for use
# or viewing without permission.
###################################################
#    Authentication Server Configuration File     #
###################################################

###################################################
# IP & Port Settings
###################################################
BindIP: "0.0.0.0"
AuthPort: 6900

###################################################
# network_threads
# Description: Number of threads for network.
# Default:        1 - (Recommended 1 thread per 1000 connections)
# Note: Cannot be less than 1.
###################################################
Network.Threads: 10

###################################################
# MD5 Password Hashing
# 0 = disabled
# 1 = MD5 (client sent)
# 2 = Bcrypt (Advanced hashing)
###################################################
pass_hash_method: 2

###################################################
# Auth Server Database Settings
###################################################
database:
    hostname: "localhost"
    port: 3306
    database: "horizon"
    username: "ragnarok"
    password: "ragnarok"
    connection_threads: 2

###################################################
# Log all requests to the login server
#
# Required for dynamic password failure ban.
###################################################
log: true
login_max_tries: 3             # Limit of failed logins before a ban is issued.
login_fail_ban_time: 10        # Time in seconds to ban an account on crossing the limit.
login_fail_check_time: 600     # Time in seconds to hold failure information.

###################################################
# Date format used to send time information to the client.
###################################################
date_format: "%Y-%m-%d %H:%M:%S"

###################################################
# Check the client's version before allowing a connection.
# Default: 0 (disabled)
###################################################
client_version: 0