
#ifndef HORIZON_ZONE_GAME_ENTITY_DEFINITIONS
#define HORIZON_ZONE_GAME_ENTITY_DEFINITIONS

enum entity_type
{
	ENTITY_PLAYER      = 0x0,
	ENTITY_NPC         = 0x1,
	ENTITY_ITEM        = 0x2,
	ENTITY_SKILL       = 0x3,
	ENTITY_UNKNOWN     = 0x4,
	ENTITY_MONSTER     = 0x5,
	ENTITY_EVENT       = 0x6,
	ENTITY_PET         = 0x7,
	ENTITY_HOMUNCULUS  = 0x8,
	ENTITY_MERCENARY   = 0x9,
	ENTITY_ELEMENTAL   = 0xA,
};

enum entity_type_mask
{
	ENTITY_MASK_PLAYER    = 0x000,
	ENTITY_MASK_NPC       = 0x001,
	ENTITY_MASK_ITEM      = 0x002,
	ENTITY_MASK_SKILL     = 0x004,
	ENTITY_MASK_UNKNOWN   = 0x008,
	ENTITY_MASK_MONSTER   = 0x010,
	ENTITY_MASK_EVENT     = 0x020,
	ENTITY_MASK_PET       = 0x040,
	ENTITY_MASK_HOMNUCLUS = 0x080,
	ENTITY_MASK_MERCNARY  = 0x0100,
	ENTITY_MASK_ELEMENTAL = 0x0200,
	ENTITY_MASK_ALL       = 0x0FFF
};

enum directions {
	DIR_NORTH      = 0,
	DIR_NORTH_WEST = 1,
	DIR_WEST       = 2,
	DIR_SOUTH_WEST = 3,
	DIR_SOUTH      = 4,
	DIR_SOUTH_EAST = 5,
	DIR_EAST       = 6,
	DIR_NORTH_EAST = 7
};

#endif /* HORIZON_ZONE_GAME_ENTITY_DEFINITIONS */
